---
title: "Reproducable Research"
output:
  pdf_document: default
  html_notebook: default
---
# Reproduceable Research

Here we outline our study into Reproducible Research to provide guidance
in the development of a Data Science / Machine Learning best practices model.
This model will provide training, guidelines, standards and expectations for
conducting projects.

The goal of this model is to provide an opinionated and easy to use process for
conducting and documenting project discoveries according to pre-defined 
standards.

This model will be especially useful for transient populations (e.g. students,
seasonal interns, workshop groups) that benefit from having predefined standards
and clear instructions on how to execute.  The provided scaffolding also
encourages effort to be focused on the analytical goals of the project
rather than infrastructure or standards.

-----

## Background Reading and Notes

### [Use of an R package to facilitate reproducible research](https://github.com/ropensci/rrrpkg)

#### Research Compendium

Using standard R Package structure is a common, familiar, and well documented standard.

## Project Arch - Steps/Processes in the standard pipeline

[https://blog.dataiku.com/2019/07/04/fundamental-steps-data-project-success](7 Fundamental Steps to Complete a Data Analytics Project)

## Workflows

### [OSEMN - A Taxonomy of Data Science](http://www.dataists.com/2010/09/a-taxonomy-of-data-science/)

[5 Steps of a Data Science Project Lifecycle](https://towardsdatascience.com/5-steps-of-a-data-science-project-lifecycle-26c50372b492)

### [Development Workflows for Data Scientists](https://resources.github.com/downloads/development-workflows-data-scientists.pdf)

### [EDA - R For Data Science](https://r4ds.had.co.nz/exploratory-data-analysis.html)

- Variance
- Typical Values
- A-Typical Values (Outliers)
- Missing Values
- Covariance
- Patterns and Seasonality

